[package]
name = "task"
version = "0.1.0"
authors = ["Mathew Robinson <chasinglogic@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "2"
taskhero = { path = "../taskhero" }
toml = "0.4"
